modLoader="javafml"
loaderVersion="[30,)"
license="MIT"
issueTrackerURL="https://github.com/Bug1312/dalekmoddev/issues"
[[mods]]
modId="dalekmoddev"
version="1.0.0"
displayName="Dalek Mod Dev Tools"
displayURL="https://github.com/Bug1312/dalekmoddev"
logoFile="logo.png"
authors="Bug1312"
description='''Tools used by Dalek Mod developers when making the mod. Perhaps they could be useful to you too, especially with datapacks!'''

[[dependencies.dalekmoddev]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dalekmoddev]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dalekmoddev]]
    modId="dalekmod"
    mandatory=true
    versionRange="[65.0.0,)"
    ordering="NONE"
    side="BOTH"